import 'package:animate_do/animate_do.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:consulting_fe/components/platform/platform_button.dart';
import 'package:consulting_fe/const/app_colors.dart';
import 'package:consulting_fe/const/app_fonts.dart';
import 'package:consulting_fe/pages/onboarding/onboarding_data.dart';
import 'package:consulting_fe/pages/onboarding/onboarding_flow.dart';

class OnboardingIntroPage extends StatefulWidget {
  const OnboardingIntroPage({super.key, this.data});
  final OnboardingData? data;

  @override
  State<OnboardingIntroPage> createState() => _OnboardingIntroPageState();
}

class _OnboardingIntroPageState extends State<OnboardingIntroPage> {
  final _scrollController = ScrollController();
  double _scrollOffset = 0;

  static const _logoMax = 80.0;
  static const _logoMin = 40.0;
  static const _scrollRange = 120.0;

  @override
  void initState() {
    super.initState();
    _scrollController.addListener(_onScroll);
  }

  void _onScroll() {
    // Allow unlimited scroll offset upwards (do not limit <0)
    setState(() => _scrollOffset = _scrollController.offset);
  }

  @override
  void dispose() {
    _scrollController.removeListener(_onScroll);
    _scrollController.dispose();
    super.dispose();
  }

  double get _logoSize {
    final t = (_scrollOffset / _scrollRange).clamp(0.0, 1.0);
    return _logoMax - (_logoMax - _logoMin) * t;
  }

  double get _logoOpacity {
    final t = (_scrollOffset / _scrollRange).clamp(0.0, 1.0);
    return 1.0 - t * 0.4;
  }

  static const _features = [
    (
      asset: 'assets/settings/traffic.svg',
      title: 'AI-Powered Plans',
      subtitle: 'Personalised workouts generated by CoachGPT just for you',
    ),
    (
      asset: 'assets/settings/car.svg',
      title: 'Daily & Weekly Structure',
      subtitle: 'Balanced workout and recovery days across the week',
    ),
    (
      asset: 'assets/summary/ready.svg',
      title: 'Nutrition Support',
      subtitle: 'Optional meal plans and diet checklists alongside training',
    ),
    (
      asset: 'assets/summary/destination.svg',
      title: 'Goal-Driven Training',
      subtitle: 'Plans tailored to your goal — from weight loss to hypertrophy',
    ),
    (
      asset: 'assets/settings/notification.svg',
      title: 'Progress Tracking',
      subtitle: 'Checklist-style tracking to keep you on target every day',
    ),
  ];

  @override
  Widget build(BuildContext context) {
    final bottomPad = MediaQuery.of(context).padding.bottom;

    return Scaffold(
      backgroundColor: AppColors.background,
      body: SafeArea(
        bottom: false,
        child: Stack(
          children: [
            SingleChildScrollView(
              controller: _scrollController,
              physics: const AlwaysScrollableScrollPhysics(
                parent: BouncingScrollPhysics(),
              ),
              padding: EdgeInsets.only(
                left: 28,
                right: 28,
                bottom: bottomPad + 220,
              ),
              child: Column(
                children: [
                  const SizedBox(height: 48),
                  FadeInDown(
                    duration: const Duration(milliseconds: 350),
                    curve: Curves.fastEaseInToSlowEaseOut,
                    child: _buildLogo(),
                  ),
                  const SizedBox(height: 32),
                  FadeInDown(
                    duration: const Duration(milliseconds: 350),
                    delay: const Duration(milliseconds: 120),
                    curve: Curves.fastEaseInToSlowEaseOut,
                    child: _buildTitle(),
                  ),
                  const SizedBox(height: 36),
                  ...List.generate(_features.length, (i) {
                    return FadeInDown(
                      duration: const Duration(milliseconds: 300),
                      delay: Duration(milliseconds: 200 + i * 60),
                      curve: Curves.fastEaseInToSlowEaseOut,
                      child: _buildFeatureRow(_features[i]),
                    );
                  }),
                ],
              ),
            ),
            Positioned(
              left: 24,
              right: 24,
              bottom: bottomPad + 20,
              child: FadeInDown(
                duration: const Duration(milliseconds: 350),
                delay: const Duration(milliseconds: 550),
                curve: Curves.fastEaseInToSlowEaseOut,
                child: PlatformButton(
                  text: 'Get Started',
                  onPressed: () {
                    Navigator.of(context).push(
                      PageRouteBuilder(
                        pageBuilder: (_, __, ___) => OnboardingFlow(
                          data: widget.data ?? const OnboardingData(),
                        ),
                        transitionsBuilder: (_, animation, __, child) =>
                            FadeTransition(opacity: animation, child: child),
                        transitionDuration: const Duration(milliseconds: 400),
                      ),
                    );
                  },
                  isProminentGlass: true,
                  height: 56,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildLogo() {
    final size = _logoSize;
    return Opacity(
      opacity: _logoOpacity,
      child: Container(
        width: size,
        height: size,
        decoration: BoxDecoration(
          boxShadow: [
            BoxShadow(
              color: AppColors.mainPoint.withValues(alpha: 0.12),
              blurRadius: 20,
              offset: const Offset(0, 6),
            ),
          ],
        ),
        child: Image.asset(
          'assets/login/light_icon.png',
          width: size,
          height: size,
        ),
      ),
    );
  }

  Widget _buildTitle() {
    return const Column(
      children: [
        Text(
          'Meet CoachGPT',
          style: TextStyle(
            fontFamily: AppFonts.normal,
            fontSize: 30,
            fontWeight: FontWeight.w800,
            color: AppColors.textPrimary,
            height: 1.2,
          ),
        ),
        SizedBox(height: 8),
        Text(
          'Your personal AI fitness coach.\nBuilds plans around your life.',
          textAlign: TextAlign.center,
          style: TextStyle(
            fontFamily: AppFonts.normal,
            fontSize: 15,
            fontWeight: FontWeight.w500,
            color: AppColors.textSecondary,
            height: 1.5,
          ),
        ),
      ],
    );
  }

  Widget _buildFeatureRow(
    ({String asset, String title, String subtitle}) feature,
  ) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 20),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SvgPicture.asset(
            feature.asset,
            width: 26,
            height: 26,
            colorFilter: const ColorFilter.mode(
              AppColors.accent,
              BlendMode.srcIn,
            ),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  feature.title,
                  style: const TextStyle(
                    fontFamily: AppFonts.normal,
                    fontSize: 16,
                    fontWeight: FontWeight.w700,
                    color: AppColors.textPrimary,
                  ),
                ),
                const SizedBox(height: 2),
                Text(
                  feature.subtitle,
                  style: const TextStyle(
                    fontFamily: AppFonts.normal,
                    fontSize: 14,
                    fontWeight: FontWeight.w400,
                    color: AppColors.textSecondary,
                    height: 1.4,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
